# Generated by /build/scold/hypogeal-twilight/libexec/autotools-local-preconfigure at 2019-03-19 18:34:25-07:00
with_hypogeal_twilight=/build/scold/hypogeal-twilight
# no setting was preestablished for vernacular-doggerel, so it will have to be discovered at configure time
# no setting was preestablished for incendiary-sophist, so it will have to be discovered at configure time
