#!/bin/bash
#
# The full nearby build for developers
#
#   buildconf
#   configure
#   make [all]
#   make check
#
# Usage:
#
#   ./maintenance/nearby     (no options)
#
# Usage:
#
#   prefix=/exp/hyperledger/fabric \
#   with_std_hyperledger_fabric=/opt/hyperledger/fabric \
#   with_std_tunitas=/opt/tunitas \
#   with_temerarious_flagship=/opt/tunitas \
#   ./maintenance/nearby
# 
# Usage:
#
#   prefix=/exp/hyperledger/fabric \
#   with_std_tunitas=no \
#   with_std_hyperledger_fabric=no \
#   with_hyperledger_fabric=/build/fabric-sdk-c++ \
#   with_tunitas_basics=/build/tunitas/tunitas-basics \
#   with_temerarious_flagship=/build/tunitas/temerarious-flagship \
#   ./maintenance/nearby
#
# /opt/scold              - The S.C.O.L.D. module "with" variables default.
# /opt/tunitas            - The Tunitas "with" variables default.
# /opt/hyperledger/fabric - The Hyperledger Fabric "with" variables default.
#
cd ${0%/*}/.. || exit 70
: ${prefix:=/exp/hyperledger/fabric}
: ${with_siblings:=${PWD%/*}}
: ${with_submodules:=no}
# with_external is deprecated, it was used by hypogeal-twilight in 0.4?? (... uh 0.42?)
if [[ -d ${PWD%/*}/nearby ]] && [[ -z $with_nearby ]] ; then
    : ${with_nearby:=${PWD%/*}/nearby} # all the development copies are in a single .../nearby area
    : ${with_tunitas_nearby:=${with_nearby?}}
    : ${with_scold_nearby:=${with_nearby?}}
    : ${with_fabric_nearby:=${with_nearby?}}
elif [[ -d /build ]] ; then
    : ${with_nearby:=/build} # every major component source is spread out in its own development tree
    : ${with_tunitas_nearby:=${with_nearby?}/tunitas}
    : ${with_scold_nearby:=${with_nearby?}/scold}
    : ${with_fabric_nearby:=${with_nearby?}/others/Hyperledger/Fabric}
else
    : ${with_nearby:=/opt}
    : ${with_tunitas_nearby:=${with_nearby?}/tunitas}
    : ${with_scold_nearby:=${with_nearby?}/scold}
    : ${with_fabric_nearby:=${with_nearby?}/hyperledger/fabric}
fi
# [[FIXTHIS]] these should become named s/std_/opt_/g as the --std- prefix has become misdirecting
: ${with_std_scold:=$with_scold_nearby}
: ${with_std_tunitas:=$with_tunitas_nearby}
: ${with_std_hyperledger_fabric:=$with_fabric_nearby}
# These need to match 1-for-1 the enablements in configure.ac
: ${with_hypogeal_twilight:=${with_scold_nearby?}/hypogeal-twilight}
: ${with_temerarious_flagship:=${with_tunitas_nearby?}/temerarious-flagship}
: ${with_module_json:=${with_scold_nearby?}/module-json}
: ${with_module_nonstd:=${with_scold_nearby?}/module-nonstd}
: ${with_module_rigging:=${with_scold_nearby?}/module-rigging}
: ${with_module_std:=${with_scold_nearby?}/module-std}
: ${with_module_sys:=${with_scold_nearby?}/module-sys}
: ${with_module_string:=${with_scold_nearby?}/module-string}
: ${with_tunitas_basics:=${with_tunitas_nearby?}/basics}
eval \
    ${prefix:+prefix=$prefix} \
    ${with_hypogeal_twilight:+with_hypogeal_twilight=$with_hypogeal_twilight} \
    ${with_temerarious_flagship:+with_temerarious_flagship=$with_temerarious_flagship} \
    ./buildconf &&
./configure \
    --enable-configure-verbose \
    --disable-mock-build \
    ${prefix:+--prefix=$prefix} \
    ${with_scold_nearby:+--with-nearby=$with_scold_nearby} ${with_external:+--with-external=$with_external} \
    ${with_submodules:+--with-submodules=$with_submodules} \
    ${with_hypogeal_twilight:+--with-hypogeal-twilight=$with_hypogeal_twilight} \
    ${with_temerarious_flagship:+--with-temerarious-flagship=$with_temerarious_flagship} \
    ${with_module_json:+--with-module-json=$with_module_json} \
    ${with_module_nonstd:+--with-module-nonstd=$with_module_nonstd} \
    ${with_module_posix:+--with-module-posix=$with_module_posix} \
    ${with_module_rigging:+--with-module-rigging=$with_module_rigging} \
    ${with_module_std:+--with-module-std=$with_module_std} \
    ${with_module_string:+--with-module-string=$with_module_string} \
    ${with_module_sys:+--with-module-sys=$with_module_sys} \
    ${with_tunitas_basics:+--with-tunitas-basics=$with_tunitas_basics} \
    ${with_std_hyperledger_fabric:+--with-std-hyperledger-fabric=$with_std_hyperledger_fabric} \
    ${with_std_tunitas:+--with-std-tunitas=$with_std_tunitas} \
    ${with_std_scold:+--with-std-scold=$with_std_scold} \
    ${end} &&
make &&
make check &&
echo OK DONE
